### ISSUE TITLE
Update install documentation to Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by sekjal** [iobridge/thingspeak#16]
Ubuntu 11.10 and 10.10 are past end of life according to https://wiki.ubuntu.com/Releases.  Ubuntu 12.04.2 is the current LTS release with an end of life scheduled for 2017.  Install documentation, and possibly the Rakefile, should be updated to reflect the latest version changes to the prerequisites.

**Comment by sidaga** [comment]
sudo apt-get update
sudo apt-get -y install build-essential ruby1.9.3 git mysql-server mysql-client libmysqlclient-dev libxml2-dev libxslt-dev
sudo gem install rails -V
git clone https://github.com/iobridge/thingspeak.git
cp thingspeak/config/database.yml.example thingspeak/config/database.yml
cd thingspeak
bundle install
bundle exec rake db:create
bundle exec rake db:schema:load
rails server
