### ISSUE TITLE
Feature Request: Add support for JSONP

### ISSUE THREAD

**Issue by itsMagondu** [iobridge/thingspeak#31]
Hi, amazing job so far with the app. Could you please add support for JSONP? Given you already have JSON, it would be a simple tweak to add jsonp for users who are need to make cross domain calls.

**Comment by llawlor** [comment]
Hi, JSONP support is already present in ThingSpeak.  You can see an example of how it's used at https://thingspeak.com/docs/channels#get_field (click on the "JSON" response button, and look at the "callback" parameter).
